/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Tavo
 */
public class ReporteUsFech extends javax.swing.JDialog {

    /**
     * Creates new form ReporteUsFech
     */
    public ReporteUsFech(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        //imagen de logo carrito
        ImageIcon icono = new ImageIcon(getClass().getResource("/Img/carrito-de-compras_logo.png"));
        setIconImage(icono.getImage());

        // AGRUPAR RADIO BUTTONS
        bgReporte.add(rbInventario);
        bgReporte.add(rbHistorial);

        rbInventario.setSelected(true);
        cargarUsuario("productos");

        rbInventario.addActionListener(e -> cargarUsuario("productos"));
        rbHistorial.addActionListener(e -> cargarUsuario("movimientos"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgReporte = new javax.swing.ButtonGroup();
        jDateDesde = new com.toedter.calendar.JDateChooser();
        cbxUsuario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateHasta = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        rbInventario = new javax.swing.JRadioButton();
        rbHistorial = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SOFTWARE DE VENTAS");
        setAlwaysOnTop(true);

        cbxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "prueba" }));

        jLabel1.setText("Usuario:");

        jLabel2.setText("Fecha desde:");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha hasta:");

        rbInventario.setText("Inventario");

        rbHistorial.setText("Historial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateDesde, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateHasta, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbInventario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbHistorial)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbInventario)
                    .addComponent(rbHistorial))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (cbxUsuario.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario.");
            return;
        }
        if (jDateDesde.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione la fecha de inicio.");
            return;
        }
        if (jDateHasta.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione la fecha de fin.");
            return;
        }
        if (jDateHasta.getDate().before(jDateDesde.getDate())) {
            JOptionPane.showMessageDialog(this, "La fecha 'Hasta' debe ser mayor o igual a 'Desde'.");
            return;
        }
        confirmado = true;
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteUsFech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteUsFech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteUsFech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteUsFech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReporteUsFech dialog = new ReporteUsFech(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private boolean confirmado = false;

    // Carga los usuarios en el ComboBox
    private void cargarUsuario(String tabla) {

        cbxUsuario.removeAllItems();

        cbxUsuario.addItem("-Seleccionar Usuario-");
        cbxUsuario.addItem("Todos");

        try {

            Conexion con = new Conexion();
            Connection conn = con.getConnection();

            PreparedStatement ps = conn.prepareStatement(
                    "SELECT DISTINCT usuario FROM " + tabla + " ORDER BY usuario"
            );

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                String usuario = rs.getString("usuario");

                if (usuario != null && !usuario.trim().isEmpty()) {
                    cbxUsuario.addItem(usuario);
                }
            }

            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {

            System.out.println("Error cargando usuarios: " + e.getMessage());
        }
    }

    // Botón Aceptar
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {
        if (cbxUsuario.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario.");
            return;
        }
        if (jDateDesde.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una fecha.");
            return;
        }
        confirmado = true;
        dispose();
    }

    // Botón Cancelar
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        confirmado = false;
        dispose();
    }

    // Métodos para obtener los valores desde afuera
    public boolean isConfirmado() {
        return confirmado;
    }

    public String getUsuario() {
        return cbxUsuario.getSelectedItem().toString();
    }

    public java.util.Date getFecha() {
        return jDateDesde.getDate();
    }

    public java.util.Date getFechaHasta() {  // ← NUEVO
        return jDateHasta.getDate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgReporte;
    private javax.swing.JComboBox<String> cbxUsuario;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateDesde;
    private com.toedter.calendar.JDateChooser jDateHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbHistorial;
    private javax.swing.JRadioButton rbInventario;
    // End of variables declaration//GEN-END:variables

    public String getTipoReporte() {
        return rbHistorial.isSelected() ? "Historial" : "Inventario";
    }
}
