/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Proveedor;
import Modelo.UsuariosDAO;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

public class Usuarios extends javax.swing.JFrame {

    private Modelo.UsuariosDAO usuarioDAO = new Modelo.UsuariosDAO();
    private Modelo.Usuarios usuario = new Modelo.Usuarios();

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        ListarUsuarios();
        //cargador de imagen del logo
        SwingUtilities.invokeLater(() -> {
            rutaLogo = "logo_pdf.png"; // ← siempre este nombre
            mostrarLogo(rutaLogo);
        });
        
        ImageIcon icono = new ImageIcon(getClass().getResource("/Img/carrito-de-compras_logo.png"));
        setIconImage(icono.getImage());
        
        jTabbedPane1.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int placement, int runCount, int maxTabHeight) {
                return 0;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        txtCorreoUsuario = new javax.swing.JTextField();
        cbxTipo = new javax.swing.JComboBox<>();
        txtClaveUsuario = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtTelefonoUsuario = new javax.swing.JTextField();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        btnGuardarUsu = new javax.swing.JButton();
        btnActualizarUsu = new javax.swing.JButton();
        btnNuevoUsu = new javax.swing.JButton();
        btnEstadoUsu = new javax.swing.JButton();
        UsuariotxtEstado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SOFTWARE ADMINISTRATIVO DE VENTAS");

        LabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLogo.setText("LOGO");

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Correo:");

        jLabel4.setText("Tipo:");

        jLabel5.setText("Clave:");

        jLabel6.setText("Nacimiento:");

        jLabel7.setText("Teléfono:");

        jLabel8.setText("Estado:");

        jLabel9.setText("Fecha creación");

        txtIdUsuario.setEditable(false);
        txtIdUsuario.setEnabled(false);
        txtIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsuarioActionPerformed(evt);
            }
        });

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Cajero", "Bodega" }));

        jDateChooser3.setEnabled(false);

        btnGuardarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        btnGuardarUsu.setText("Guardar");
        btnGuardarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUsuActionPerformed(evt);
            }
        });

        btnActualizarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnActualizarUsu.setText("Actualizar");
        btnActualizarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUsuActionPerformed(evt);
            }
        });

        btnNuevoUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        btnNuevoUsu.setText("Nuevo");
        btnNuevoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuActionPerformed(evt);
            }
        });

        btnEstadoUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/encendido-apagado.png"))); // NOI18N
        btnEstadoUsu.setText("Estado");
        btnEstadoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoUsuActionPerformed(evt);
            }
        });

        UsuariotxtEstado.setEditable(false);

        TableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Correo", "Tipo usuario", "Nacimiento", "Teléfono", "Estado", "Creación"
            }
        ));
        TableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableUsuarios);
        if (TableUsuarios.getColumnModel().getColumnCount() > 0) {
            TableUsuarios.getColumnModel().getColumn(0).setPreferredWidth(5);
            TableUsuarios.getColumnModel().getColumn(1).setPreferredWidth(50);
            TableUsuarios.getColumnModel().getColumn(2).setPreferredWidth(50);
            TableUsuarios.getColumnModel().getColumn(3).setPreferredWidth(15);
            TableUsuarios.getColumnModel().getColumn(4).setPreferredWidth(20);
            TableUsuarios.getColumnModel().getColumn(5).setPreferredWidth(20);
            TableUsuarios.getColumnModel().getColumn(6).setPreferredWidth(10);
            TableUsuarios.getColumnModel().getColumn(7).setPreferredWidth(10);
        }

        jTabbedPane1.addTab("tab1", jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtClaveUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTelefonoUsuario)
                                            .addComponent(UsuariotxtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNuevoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGuardarUsu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnActualizarUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEstadoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtClaveUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTelefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(UsuariotxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEstadoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuarioActionPerformed

    private void btnGuardarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUsuActionPerformed
        // TODO add your handling code here:
        if (txtNombreUsuario.getText().isEmpty()
                || txtCorreoUsuario.getText().isEmpty()
                || txtClaveUsuario.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete los campos obligatorios");
            return;
        }

        // Obtener tipo según el combo
        int tipo = cbxTipo.getSelectedIndex() + 1; // Administrador=1, Cajero=2, Bodega=3

        usuario.setNombre(txtNombreUsuario.getText());
        usuario.setCorreo(txtCorreoUsuario.getText());
        usuario.setTipoUsuario(tipo);
        usuario.setPass(txtClaveUsuario.getText());
        usuario.setNacimiento(jDateChooser1.getDate());
        usuario.setTelefono(txtTelefonoUsuario.getText());

        if (usuarioDAO.Registrar(usuario)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario registrado correctamente");
            Limpiar();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar usuario");
        }
        if (usuarioDAO.Registrar(usuario)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario registrado correctamente");
            Limpiar();
            ListarUsuarios(); // ← agrega
        }
    }//GEN-LAST:event_btnGuardarUsuActionPerformed

    private void btnActualizarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuActionPerformed
        // TODO add your handling code here:
        if (txtIdUsuario.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un usuario primero");
            return;
        }
        int tipo = cbxTipo.getSelectedIndex() + 1;
        usuario.setId(Integer.parseInt(txtIdUsuario.getText()));
        usuario.setNombre(txtNombreUsuario.getText());
        usuario.setCorreo(txtCorreoUsuario.getText());
        usuario.setTipoUsuario(tipo);
        usuario.setPass(txtClaveUsuario.getText());
        usuario.setNacimiento(jDateChooser1.getDate());
        usuario.setTelefono(txtTelefonoUsuario.getText());

        if (usuarioDAO.Modificar(usuario)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente");
            Limpiar();
            ListarUsuarios();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar usuario");
        }
    }//GEN-LAST:event_btnActualizarUsuActionPerformed

    private void btnNuevoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnNuevoUsuActionPerformed

    private void btnEstadoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoUsuActionPerformed
        // TODO add your handling code here:
        int fila = TableUsuarios.getSelectedRow();

        // 🔴 Validar si seleccionó algo
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto");
            return;
        }
        //codigo provisional
        for (int i = 0; i < TableUsuarios.getColumnCount(); i++) {
            System.out.println("Columna " + i + ": " + TableUsuarios.getModel().getValueAt(fila, i));
        }

        int id = Integer.parseInt(TableUsuarios.getModel().getValueAt(fila, 0).toString());
        int estadoActual = Integer.parseInt(TableUsuarios.getModel().getValueAt(fila, 6).toString());

        // Mensaje dinámico según estado actual
        String mensaje = estadoActual == 1 ? "¿Desea desactivar este usuario?" : "¿Desea activar este usuario?";

        int confirm = JOptionPane.showConfirmDialog(this, mensaje, "Confirmar", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (usuarioDAO.EstadoUsuario(id)) {
                modelo.setRowCount(0);
                ListarUsuarios();
            } else {
                JOptionPane.showMessageDialog(null, "Error al bloquear producto");
            }
        }
        Limpiar();
        // Habilitar botones
        btnGuardarUsu.setEnabled(true);      // Activo para guardar nuevo
        btnNuevoUsu.setEnabled(true);        // Activo
        btnEstadoUsu.setEnabled(false);    // Inactivo (no hay nada seleccionado)
        btnActualizarUsu.setEnabled(false);  // Inactivo (no hay nada seleccionado)
        //tbnExcel.setEnabled(false);             // Inactivo (no hay nada seleccionado)
        //tbnPDF.setEnabled(false);              // Inactivo (no hay nada seleccionado)

        // Quitar selección de la tabla
        TableUsuarios.clearSelection();

        // Poner el foco en el primer campo
        txtIdUsuario.requestFocus();
        System.out.println("Total columnas: " + TableUsuarios.getColumnCount());
        for (int i = 0; i < TableUsuarios.getColumnCount(); i++) {
            System.out.println("Columna " + i + ": " + TableUsuarios.getModel().getValueAt(0, i));
        }

    }//GEN-LAST:event_btnEstadoUsuActionPerformed

    private void TableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUsuariosMouseClicked
        // TODO add your handling code here:
        int fila = TableUsuarios.rowAtPoint(evt.getPoint());
        if (fila < 0) {
            return;
        }

        java.util.function.Function<Object, String> safe = val -> val != null ? val.toString() : "";

        // Campos simples
        txtIdUsuario.setText(safe.apply(TableUsuarios.getValueAt(fila, 0)));       // ID
        txtNombreUsuario.setText(safe.apply(TableUsuarios.getValueAt(fila, 1)));   // Nombre
        txtCorreoUsuario.setText(safe.apply(TableUsuarios.getValueAt(fila, 2)));   // Correo
        cbxTipo.setSelectedItem(safe.apply(TableUsuarios.getValueAt(fila, 3)));
        // ── Fecha de nacimiento → jDateChooser1 (índice 4) ──
        Object fechaNac = TableUsuarios.getValueAt(fila, 4);
        if (fechaNac != null && !fechaNac.toString().isEmpty()) {
            try {
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
                jDateChooser1.setDate(sdf.parse(fechaNac.toString()));
            } catch (Exception e) {
                System.out.println("Error fecha nacimiento: " + e.getMessage());
                jDateChooser1.setDate(null);
            }
        } else {
            jDateChooser1.setDate(null);
        }
        txtTelefonoUsuario.setText(safe.apply(TableUsuarios.getValueAt(fila, 5))); // Teléfono
        UsuariotxtEstado.setText(safe.apply(TableUsuarios.getValueAt(fila, 6)));   // Estado
        Object estadoVal = TableUsuarios.getValueAt(fila, 6);
        if (estadoVal != null) {
            String estadoTexto = estadoVal.toString().trim().equals("1") ? "Activo" : "Inactivo";
            UsuariotxtEstado.setText(estadoTexto);
        } else {
            UsuariotxtEstado.setText("Desconocido");
        }
        txtClaveUsuario.setText(safe.apply(TableUsuarios.getValueAt(fila, 3))); // TipoNombre
        // ── Fecha de creación → jDateChooser3 (índice 7) ──
        Object fechaCreacion = TableUsuarios.getValueAt(fila, 7);
        if (fechaCreacion != null && !fechaCreacion.toString().isEmpty()) {
            try {
                // getCreatedAt suele traer timestamp completo
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                jDateChooser3.setDate(sdf.parse(fechaCreacion.toString()));
            } catch (Exception e) {
                // Si falla con timestamp, intentar solo fecha
                try {
                    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
                    jDateChooser3.setDate(sdf.parse(fechaCreacion.toString()));
                } catch (Exception e2) {
                    System.out.println("Error fecha creación: " + e2.getMessage());
                    jDateChooser3.setDate(null);
                }
            }
        } else {
            jDateChooser3.setDate(null);
        }

        // Fecha de nacimiento (índice 4)
        Object fechaVal = TableUsuarios.getValueAt(fila, 4);
        if (fechaVal != null && !fechaVal.toString().isEmpty()) {
            try {
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
                java.util.Date fecha = sdf.parse(fechaVal.toString());
                jDateChooser1.setDate(fecha);
            } catch (Exception e) {
                System.out.println("Error al parsear fecha nacimiento: " + e.getMessage());
                jDateChooser1.setDate(null);
            }
        } else {
            jDateChooser1.setDate(null);
        }
    }//GEN-LAST:event_TableUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    private void mostrarLogo(String nombreArchivo) {
        if (nombreArchivo != null && !nombreArchivo.isEmpty()) {

            java.net.URL ruta = getClass().getResource("/Img/" + nombreArchivo);

            if (ruta != null) {

                ImageIcon imagen = new ImageIcon(ruta);

                int ancho = LabelLogo.getWidth() > 0
                        ? LabelLogo.getWidth()
                        : LabelLogo.getPreferredSize().width;

                int alto = LabelLogo.getHeight() > 0
                        ? LabelLogo.getHeight()
                        : LabelLogo.getPreferredSize().height;

                if (ancho <= 0) {
                    ancho = 158;
                }

                if (alto <= 0) {
                    alto = 158;
                }

                Image imgEscalada = imagen.getImage().getScaledInstance(
                        ancho,
                        alto,
                        Image.SCALE_SMOOTH
                );

                LabelLogo.setText("");
                LabelLogo.setIcon(new ImageIcon(imgEscalada));

            } else {

                System.out.println("No se encontró la imagen: " + nombreArchivo);

                LabelLogo.setIcon(null);
                LabelLogo.setText("Logo no encontrado");
            }

        } else {

            LabelLogo.setIcon(null);
            LabelLogo.setText("Aquí va su logo");
            LabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        }
    }

    private String rutaLogo = "";

    private void Limpiar() {
        txtIdUsuario.setText("");
        txtNombreUsuario.setText("");
        txtCorreoUsuario.setText("");
        txtClaveUsuario.setText("");
        txtTelefonoUsuario.setText("");
        UsuariotxtEstado.setText("1");
        cbxTipo.setSelectedIndex(0);
        jDateChooser1.setDate(null);
        jDateChooser3.setDate(new java.util.Date()); // ← siempre fecha actual
    }

    public void ListarUsuarios() {
        List<Modelo.Usuarios> ListaUsu = usuarioDAO.Listar();
        modelo = (DefaultTableModel) TableUsuarios.getModel();
        modelo.setRowCount(0);

        Object[] ob = new Object[8];
        for (int i = 0; i < ListaUsu.size(); i++) {
            ob[0] = ListaUsu.get(i).getId();
            ob[1] = ListaUsu.get(i).getNombre();
            ob[2] = ListaUsu.get(i).getCorreo();
            ob[3] = ListaUsu.get(i).getTipoNombre();   // ← era getTipoUsuario()
            ob[4] = ListaUsu.get(i).getNacimiento();
            ob[5] = ListaUsu.get(i).getTelefono();
            ob[6] = ListaUsu.get(i).getEstado();
            ob[7] = ListaUsu.get(i).getCreatedAt();
            modelo.addRow(ob);
        }
        TableUsuarios.setModel(modelo);
        aplicarColorEstadoUsu(); // lo llamas desde aquí

        // Activa o desactiva los botones según sea el estado del cliente
        TableUsuarios.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && TableUsuarios.getSelectedRow() != -1) {

                int fila = TableUsuarios.getSelectedRow();
                Object estado = TableUsuarios.getValueAt(fila, 6);

                int estadoVal = Integer.parseInt(estado.toString().trim());

                if (estadoVal == 1) {
                    btnEstadoUsu.setEnabled(true);    // Boton Activo
                    btnGuardarUsu.setEnabled(true);     // Boton Activo
                    btnNuevoUsu.setEnabled(true);       // Boton Activo
                    btnActualizarUsu.setEnabled(true); // Boton Activo
                } else {
                    btnEstadoUsu.setEnabled(true);    // Boton Activo
                    btnGuardarUsu.setEnabled(false);    // Boton inactivo
                    btnNuevoUsu.setEnabled(false);      // Boton inactivo
                    btnActualizarUsu.setEnabled(false);// Boton inactivo
                }
            }
        });
    }

    private String tipoNombre;

    private void aplicarColorEstadoUsu() {
        TableUsuarios.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                java.awt.Component c = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                Object estado = table.getModel().getValueAt(row, 6); // ← índice 10

                if (!isSelected) {
                    String estadoStr = estado.toString().trim();
                    if (!estadoStr.isEmpty()) { // ← validar que no esté vacío
                        int estadoVal = Integer.parseInt(estadoStr);
                        if (estadoVal == 1) {
                            c.setBackground(new java.awt.Color(232, 255, 234));
                            c.setForeground(new java.awt.Color(0, 120, 0));
                        } else {
                            c.setBackground(new java.awt.Color(189, 189, 189));
                            c.setForeground(new java.awt.Color(245, 73, 39));
                        }
                    }
                }
                return c;
            }
        });

        TableUsuarios.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && TableUsuarios.getSelectedRow() != -1) {

                int fila = TableUsuarios.getSelectedRow();
                Object estado = TableUsuarios.getValueAt(fila, 6);

                int estadoVal = Integer.parseInt(estado.toString().trim());

                if (estadoVal == 1) {
                    btnEstadoUsu.setEnabled(true);    // Boton Activo
                    btnGuardarUsu.setEnabled(false);     // Boton inactivo
                    btnNuevoUsu.setEnabled(true);       // Boton Activo
                    btnActualizarUsu.setEnabled(true); // Boton Activo
                    //tbnExcel.setEnabled(true);// Boton Activo
                    //tbnPDF.setEnabled(true);// Boton Activo
                } else {
                    btnEstadoUsu.setEnabled(true);    // Boton Activo
                    btnGuardarUsu.setEnabled(false);    // Boton inactivo
                    btnNuevoUsu.setEnabled(true);      // Boton Activo
                    btnActualizarUsu.setEnabled(false);// Boton inactivo
                    //tbnExcel.setEnabled(false);// Boton inactivo
                    //tbnPDF.setEnabled(false);// Boton inactivo
                }
            }
        });

        // Ocultar columna ID (índice 0)
        TableUsuarios.getColumnModel().getColumn(0).setMinWidth(0);
        TableUsuarios.getColumnModel().getColumn(0).setMaxWidth(0);
        TableUsuarios.getColumnModel().getColumn(0).setPreferredWidth(0);

        // Ocultar columna Estado (índice 10)
        TableUsuarios.getColumnModel().getColumn(6).setMinWidth(0);
        TableUsuarios.getColumnModel().getColumn(6).setMaxWidth(0);
        TableUsuarios.getColumnModel().getColumn(6).setPreferredWidth(0);
    }

    private javax.swing.table.DefaultTableModel modelo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JTable TableUsuarios;
    private javax.swing.JTextField UsuariotxtEstado;
    private javax.swing.JButton btnActualizarUsu;
    private javax.swing.JButton btnEstadoUsu;
    private javax.swing.JButton btnGuardarUsu;
    private javax.swing.JButton btnNuevoUsu;
    private javax.swing.JComboBox<String> cbxTipo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtClaveUsuario;
    private javax.swing.JTextField txtCorreoUsuario;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtTelefonoUsuario;
    // End of variables declaration//GEN-END:variables
}
